# netlify.toml

[build]
  command   = "npm run build"
  publish   = "dist"

[functions]
  # Folder where your function files live
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/data/**"]

[dev]
  # Local dev server
  framework = "astro"
  port = 8888
  functionsPort = 9999
